### ISSUE TITLE
Enable associating schema type information with existing <N> tree or subtree via (re)validation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TIBCOSoftware/genxdm#101]
```
It would be nice to have cursor-based validation (particularly if we follow 
through on the cursor changes that eric's been working on). One thing that 
cursor-oriented transit of a document does is to inherently tie the source of 
events (in ContentHandler or SequenceHandler) to the node of origin.

The javadoc for validate suggests that it can return the same tree supplied, 
only with type annotations and possibly typed values. In practice, it's not 
really possible to do this when attaching Model.stream() to a ContentHandler or 
SequenceHandler, because it's too difficult to find the <N>ode associated with 
each event's origin. With Cursor, state is carried--it's *easy*. And we can 
leave it up to each bridge to decide whether to modify an existing tree or 
create a new one.
```

Original issue reported on code.google.com by `aale...@gmail.com` on 20 Sep 2012 at 7:09

**Comment by aaletal** [comment]
Further information:

We can do in-tree validation using the current ContentGenerator-based validation method, without requiring that we drop the use of SequenceHandler. We simply have to have the same object implement both ContentGenerator and SequenceHandler (or SequenceBuilder, which is prolly the validator's signature).

To do this, we need a new Feature, prolly something-something-validation-in-tree (prolly a sub-pattern of typed support). When a bridge advertises this feature as supported, a new method on TypedContext, something like newTreeValidator(N) would supply a pre-positioned ContentGenerator that also acts as a SequenceHandler/Builder.

In addition to the TreeValidator, a bridge supporting the new functionality would also support new APIs, or would use internal functionality allowing it to set the annotation and the typed value for each node.

Or something like that.

**Comment by aaletal** [comment]
Oops. This is done, as of 1.2.2 (I think?), when we provided in-tree validation. That didn't change any interfaces (making it a really cool trick, you know), so I overlooked revisiting and closing this.

If a bridge supports in-tree validation via the cursor-argument validate() method, it also supports partial-tree validation.
