### ISSUE TITLE
Add XPath support via the javax.xml.xpath APIs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TIBCOSoftware/genxdm#51]
```
It looks like the javax.xml.xpath APIs should be sufficient to support a GenXDM 
based XPath implementation.

Even better, the java.xml.xpath.XPathFactory method isObjectModelSupported() 
can return true for all available bridges....

```

Original issue reported on code.google.com by `eric%tib...@gtempaccount.com` on 29 Mar 2011 at 8:29

**Comment by aaletal** [comment]
Marked as enhancement and assigned to me, and now closed as wontfix, because (first) the javax.xml.xpath APIs suck enough that no one is asking for them, and (second) we originally adopted the XPath 1.0 API that we have because this stuff was terrible. So ... let's be done with revisiting that.
